apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/app/
images:
- name: rpc-client
  newName: docker.io/az871209/arch
  newTag: rpc-client-5590e2bc8541eb73447902e29ed7093ee334a1b3
- name: rpc-server
  newName: docker.io/az871209/arch
  newTag: rpc-server-eec9c90248eb2a5a0f8a33732988570b62f0da45
