apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/app/
images:
- name: rpc-client
  newName: docker.io/az871209/arch
- name: rpc-server
  newName: docker.io/az871209/arch
