apiVersion: v1
kind: ConfigMap
metadata:
  name: rpc-server
data:
  GRPC_PORT: "50051"
  MAX_RECV_MSG_SIZE: "4194304" # 4MB
  MAX_SEND_MSG_SIZE: "4194304" # 4MB
  ENABLE_REFLECTION: "true"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  CACHE_URL: "valkey://valkey.storage.svc.cluster.local:6379"
  CACHE_MAX_CONNS: "10"
  CACHE_MIN_CONNS: "2"
  CACHE_MAX_IDLE_TIME: "300"
  CACHE_MAX_LIFETIME: "3600"
  DB_MAX_CONNS: "25"
  DB_MIN_CONNS: "5"
  DB_MAX_IDLE_TIME: "300"
  DB_MAX_LIFETIME: "3600"
  TRACING_ENABLED: "true"
  TRACING_SERVICE_NAME: "rpc-server.arch"
  TRACING_SERVICE_VERSION: "1.0.0"
  TRACING_COLLECTOR_URL: "jaeger-collector.observability.svc.cluster.local:4317"
