apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rpc-server
spec:
  replicas: 3
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: rpc-server
            routes:
              - primary
          destinationRule:
            name: rpc-server
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: rpc-server
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: arch
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpc-server
